export const POLICIES = {
  USER_VIEW_ALL: "USER_VIEW_ALL",
  USER_VIEW_SELF: "USER_VIEW_SELF",
  USER_DELETE: "USER_DELETE",
  USER_CREATE: "USER:CREATE",
  USER_UPDATE: "USER:UPDATE", 
  ORDER_CREATE: "ORDER:CREATE", 
  PRODUCT_VIEW: "PRODUCT:VIEW",
  ORDER_VIEW_SELF: "ORDER:VIEW_SELF"
};